name: Create new build release

on:
  push:
    branches:
    - main
    
jobs:
  build-project:  
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload static content
        uses: actions/upload-artifact@v3
        with: 
          name: static-content
          path: .dist/
    release-project:
      name: Release Project
      runs-on: ubuntu-latest
      needs: build-project
      steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: static-content
      - name: Archive content
        uses: thedoctor0/zip-release@master
        with:
          filename: chrome-extension.zip
      - name: Create Github release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: chrome-extension.zip
          asset_name: chrome-extension-v${{ github.run_number }}.zip
          asset_content_type: application/zip
